name: "CI"

on:
  pull_request:
    branches: 
      - main

jobs:
  lint-json:
    name: "Lint JSON"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -qq update
      - run: sudo apt-get --quiet --assume-yes install jsonlint
      - run: jsonlint-php *.json
