name: "Lint JSON"

on:
  pull_request:
    branches:
      - main

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -qq update
      - run: sudo apt-get --quiet --assume-yes install jsonlint
      - run: jsonlint -v *.json >> $GITHUB_STEP_SUMMARY
