name: "Lint JSON"

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  lint-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get -qq update
      - run: sudo apt-get --quiet --assume-yes install jsonlint
      - run: $HOME/.local/bin/jsonlint -v en.json
